baseURL = ''
languageCode = 'fi'
defaultContentLanguage = 'fi'
title = 'Icetribe - Pop & Rock -bilebändi'
theme = 'ananke'

[menu]
  [[menu.main]]
    name = "Etusivu"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Tietoa"
    url = "/about/"
    weight = 2

  [[menu.main]]
    name = "Soitossa"
    url = "/repertuaari/"
    weight = 3

  [[menu.main]]
    name = "Uutiset"
    url = "/posts/"
    weight = 4

  [[menu.main]]
    name = "Yhteystiedot"
    url = "/yhteystiedot/"
    weight = 5

# Hugo kuvan prosessointi asetukset
[imaging]
  resampleFilter = "lanczos"
  quality = 85
  anchor = "smart"
  
[imaging.webp]
  quality = 85
  lossless = false

[params]
  read_more_copy = "Lue lisää"

# Ananke teeman sosiaalinen media
[params.ananke]
  show_recent_posts = false
[params.ananke.social]

[params.ananke.social.follow]
networks = ["facebook", "instagram", "soundcloud"]

# Sosiaalisten medioiden profiilit
[params.ananke.social.facebook]
profilelink = "https://www.facebook.com/Icetribe"

[params.ananke.social.instagram] 
username = "icetribe_official"

[params.ananke.social.soundcloud]
profilelink = "https://soundcloud.com/icetribe"

# SoundCloud määritelmä (puuttuu Anankesta)
[params.ananke.social.networks.soundcloud]
slug = "soundcloud"
label = "SoundCloud"
color = "#ff5500"
profile = "https://soundcloud.com/%s"
icon = "soundcloud"
